import type { Club } from "./types";

export const IFK_GOTEBORG: Club = {
  id: "ifk-goteborg",
  name: "IFK Göteborg",
  shortName: "IFK",
  nicknames: ["Blåvitt", "Änglarna", "Kamraterna"],
  city: "Göteborg",
  arena: "Gamla Ullevi",
  founded: 1904,
  newsQuery: '"IFK Göteborg" OR Blåvitt',
  tagline: "Hela stadens lag",
  tone: "Stolt, göteborgsk och lite glimten i ögat – hela stadens lag. Humor mot motståndare är okej, aldrig hat eller personangrepp.",
  palette: [
    { name: "IFK-blå", hex: "#234B9A" },
    { name: "Vit", hex: "#FFFFFF" },
    { name: "Mörkblå", hex: "#1A3770" },
    { name: "Sköldblå", hex: "#197BC4" },
    { name: "Svart (neutral)", hex: "#0A0A0A" },
  ],
  crestColors: ["#197BC4", "#FBC323", "#FFFFFF"],
  brand: {
    crest: { farg: "skold-farg.png", svart: "skold-svart.png", vit: "skold-vit.png" },
    fonts: { brand: "Akkurat Black", web: "Source Sans Pro" },
    source: "ifkgoteborg.se",
  },
  forbiddenColors: [
    { name: "Grön", words: ["green", "grön", "grönt", "gröna"], reason: "Förknippas med GAIS och Hammarby" },
    { name: "Röd", words: ["red", "röd", "rött", "röda"], reason: "Förknippas med Örgryte IS" },
    { name: "Gul", words: ["yellow", "gul", "gult", "gula", "gold", "golden"], reason: "Förknippas med AIK – guldet finns bara i den officiella skölden" },
  ],
  bannedWords: ["hata", "hat", "död", "jävla", "fitta", "kuk", "bög", "idiot"],
  maxSloganLength: 32,
  rules: [
    "Endast klubbens färger: IFK-blå #234B9A, mörkblå #1A3770, sköldblå #197BC4, vit och svart som neutral.",
    "Endast den officiella klubbskölden – i fullfärg, eller svart/vit vid tryck i en färg. Den får aldrig ändras, beskäras eller färgläggas om. AI ritar aldrig sköld eller logga.",
    "Guldet (#FBC323) förekommer bara i skölden, aldrig i motiv eller text.",
    "Inga spelares namn, ansikten eller nummer – även om de nämns i nyheterna.",
    "Humor mot motståndare är okej, men inga svordomar, hat eller personangrepp.",
    "Slogan max 32 tecken, på svenska eller göteborgska.",
    "Motiv ska fungera i digitaltryck (DTG): max tre färger, tydliga former, inga fotografier.",
  ],
  intersportShopUrl: "https://www.intersport.se/klubbshop/ifk-goteborg",
  contactPerson: { role: "Klubbens merchandiseansvarige", channel: "e-post" },
  sources: {
    website: "https://ifkgoteborg.se",
    sportsDbTeamId: "134161",
    youtubeUser: "Kanal1904",
    podcastSearch: ["Blåvitt", "IFK Göteborg"],
    weather: { place: "Göteborg", lat: 57.71, lon: 11.97 },
  },
  agent: {
    name: "Blåvitt-agenten",
    mission:
      "Skapa säljande, äkta supportermerch för IFK Göteborg helt automatiskt och publicera i klubbshoppen hos Intersport – utan att klubben behöver göra något.",
    guidelines: [
      "Följ IFK Göteborgs färger och grafiska profil utan undantag i standardläge.",
      "Använd bara IFK:s egna symboler: den officiella skölden, ränderna, Änglarna, Gamla Ullevi och göteborgska uttryck.",
      "Allt ska kännas som något en riktig Blåvitt-supporter vill bära – inte som reklam.",
      "Publicera bara det granskaren ger minst 8 av 10 i säljbarhet, realism och varumärkespassning.",
      "Aldrig spelarnamn, ansikten eller nummer. Aldrig hat, svordomar eller personangrepp.",
    ],
    satire: {
      allowed: true,
      when: "Derbyn, segrar mot rivaler och stormatcher – när supportrarna själva skämtar.",
      rules: [
        "Satir och memes får driva med motståndaren – med glimten i ögat, aldrig elakt.",
        "Motståndarens färger får användas som skämtelement (max en tredjedel av motivet).",
        "Aldrig motståndarens sköld, logotyp eller varumärken – bara färger, smeknamn och allmänna symboler.",
        "IFK ska alltid vara vinnaren i skämtet. Inget som kan uppfattas som hot eller trakasserier.",
      ],
      extraColors: [
        { name: "Svart (satir)", hex: "#111111" },
        { name: "AIK-gul (satir)", hex: "#FFD100" },
        { name: "Grön (satir)", hex: "#00843D" },
      ],
      maxPerRun: 2,
    },
    review: { minMotifSales: 7, minSales: 8, minRealism: 8, minBrandFit: 8, maxRetries: 1 },
    autopilot: { maxProductsPerRun: 3, maxRunsPerWeek: 4, publish: "auto" },
  },
};

export const CIRCLE_K: Club = {
  id: "circle-k",
  kind: "brand",
  name: "Circle K",
  shortName: "Circle K",
  nicknames: ["Circle K"],
  city: "Sverige",
  arena: "Sverige",
  founded: 1951,
  newsQuery: '"Circle K"',
  tagline: "Alltid på vägen",
  tone: "Varm, vardaglig och hjälpsam med glimten i ögat – kaffet, korven, bilresan och stationen som lyser i mörkret. Aldrig kaxig mot konkurrenter, aldrig om drivmedelspriser eller politik.",
  palette: [
    { name: "Circle K-röd", hex: "#DA291C" },
    { name: "Orange", hex: "#ED8B00" },
    { name: "Vit", hex: "#FFFFFF" },
    { name: "Mörkgrå", hex: "#414141" },
  ],
  crestColors: ["#EE2E24", "#FFFFFF"],
  brand: {
    crest: { farg: "skold-farg.png", svart: "skold-svart.png", vit: "skold-vit.png" },
    fonts: { brand: "ACT Easy", web: "Source Sans Pro" },
    source: "circlek.se",
  },
  forbiddenColors: [
    { name: "Grön", words: ["green", "grön", "grönt", "gröna"], reason: "Förknippas med Preem" },
    { name: "Blå", words: ["blue", "blå", "blått", "blåa", "navy"], reason: "Förknippas med OKQ8 och Ingo" },
    { name: "Gul", words: ["yellow", "gul", "gult", "gula", "gold", "golden"], reason: "Förknippas med Shell och St1" },
  ],
  competitors: ["okq8", "q8", "preem", "st1", "shell", "ingo", "tanka", "uno-x"],
  bannedWords: ["hata", "hat", "död", "jävla", "fitta", "kuk", "bög", "idiot"],
  maxSloganLength: 32,
  rules: [
    "Endast Circle K:s färger: röd #DA291C, orange #ED8B00, vit och mörkgrå #414141 som neutral.",
    "Endast den officiella Circle K-loggan – i rött, eller svart/vit vid tryck i en färg. Den får aldrig ändras, beskäras eller färgläggas om. AI ritar aldrig logga.",
    "Aldrig konkurrenters namn, loggor eller färger (OKQ8, Preem, St1, Shell, Ingo).",
    "Inga verkliga personer, kändisar eller medarbetares namn.",
    "Inga budskap om drivmedelspriser, politik eller klimatlöften.",
    "Slogan max 32 tecken, på svenska.",
    "Motiv ska fungera i digitaltryck (DTG): max tre färger, tydliga former, inga fotografier.",
  ],
  intersportShopUrl: "https://www.circlek.se/merch",
  contactPerson: { role: "Circle K:s marknadsavdelning", channel: "e-post" },
  sources: {
    website: "https://www.circlek.se",
    youtubeChannelId: "UCNwQMgSm3U5A8gGn__XIDEg",
    pressRss: { name: "Circle K pressrum", url: "https://via.tt.se/rss/releases/latest?publisherId=3237124" },
    offersUrl: "https://www.circlek.se/erbjudanden",
    weather: { place: "Stockholm", lat: 59.33, lon: 18.07 },
  },
  copy: {
    maker: "Circle K",
    product: "Merch",
    pickTitle: "Välj varumärke.",
    pickPlaceholder: "Sök, t.ex. Circle K",
    pickEmpty: "Just nu finns Circle K.",
    newsPlaceholder: "Klistra in länk till en nyhet om Circle K",
    customPlaceholder: "Något eget? T.ex. Kaffefredag",
    org: "Circle K:s",
    listening: "Lyssnar av nyheter, pressrum, erbjudanden och väder för",
    shopName: "Circle K-shoppen",
    shopSupport: "Tryckt på beställning · Hämtas på din station",
    logoWord: "logga",
    loaderLines: [
      "Kaffet bryggs…",
      "Korven vänds på grillen…",
      "Tanken fylls…",
      "K-Freeze blandas…",
      "Vindrutan putsas…",
      "Isskrapan hittas i handskfacket…",
      "Lamporna tänds på stationen…",
      "Nästa stopp: Circle K",
    ],
    loaderDone: "Trevlig resa!",
    navLinks: false,
  },
  agent: {
    name: "Circle K-agenten",
    mission:
      "Skapa säljande merch med Circle K:s egna ikoner – kaffet, korven, bilresan och stationen – helt automatiskt och alltid i Circle K:s grafiska profil.",
    guidelines: [
      "Följ Circle K:s färger och grafiska profil utan undantag.",
      "Använd Circle K:s egna ikoner: kaffekoppen, korv med bröd, K-Freeze, bilresan, vägen, stationens ljus i mörkret och isskrapan en frostig morgon.",
      "Allt ska kännas som något en stamkund vill ha – kul, vardagligt och lite nostalgiskt – inte som reklam.",
      "Publicera bara det granskaren ger minst 8 av 10 i säljbarhet, realism och varumärkespassning.",
      "Aldrig konkurrenter, verkliga personer eller budskap om priser och politik.",
    ],
    satire: { allowed: false, when: "", rules: [], extraColors: [], maxPerRun: 0 },
    review: { minMotifSales: 7, minSales: 8, minRealism: 8, minBrandFit: 8, maxRetries: 1 },
    autopilot: { maxProductsPerRun: 3, maxRunsPerWeek: 2, publish: "auto" },
  },
};

export const CLUBS: Record<string, Club> = { [IFK_GOTEBORG.id]: IFK_GOTEBORG, [CIRCLE_K.id]: CIRCLE_K };
